name: "DGT tag split action"
description: "Get a version number from a specific tag"
author: "Gert Meulyzer"
inputs:
  refname:
    description: "The tag needs to be in here."
    default: "${{ github.ref_name }}"
outputs:
  versionnr:
    description: "The version number detected in the action."
runs:
  using: "docker"
  image: "Dockerfile"
